compilation:
  network: default
  reuse_compilation_vms: true
  vm_type: default
  workers: 1
disk_types:
- disk_size: 1024
  name: default
networks:
- name: default
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.0.0/24
    reserved:
    - 10.244.0.1
vm_types:
- cloud_properties:
    ephemeral_disk:
      size: 1024
      type: gp2
  name: default
