azs:
- cloud_properties:
    datacenters:
    - clusters:
      - cl:
          resource_pool: BOSH
      name: dc
  name: z1
compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: compilation
  workers: 5
disk_types:
- disk_size: 1024
  name: default
networks:
- name: default
  subnets:
  - azs:
    - z1
    cloud_properties:
      name: VM Network
    gateway: 10.0.9.1
    range: 10.0.9.0/24
    reserved:
    - 10.0.9.1-10.0.9.151
    - 10.0.9.160-10.0.9.170
    - 10.0.9.180-10.0.9.255
    static:
    - 10.0.9.152-10.0.9.155
  type: manual
- name: guest
  subnets:
  - azs:
    - z1
    cloud_properties:
      name: Guest
    gateway: 10.2.0.1
    range: 10.2.0.0/24
    reserved:
    - 10.2.0.1-10.2.0.240
    - 10.2.0.251-10.2.0.255
  type: manual
vm_types:
- cloud_properties:
    cpu: 1
    disk: 1024
    ram: 512
  name: small
- cloud_properties:
    cpu: 4
    disk: 3072
    ram: 4096
  name: compilation
- cloud_properties:
    cpu: 4
    disk: 65536
    ram: 8192
  name: concourse-workers
