vm_types:
- name: small
  cloud_properties:
    cpu: 1
    ram: 512
    disk: 1024
- name: compilation
  cloud_properties:
    cpu: 4
    ram: 4096
    disk: 3072

disk_types:
- name: default
  disk_size: 1024

networks:
- name: internetless
  type: manual
  subnets:
  - range: 192.168.0.0/24
    gateway: 192.168.0.1
    static: [192.168.0.3, 192.168.0.4]
    cloud_properties:
      name: opaque

compilation:
  workers: 5
  reuse_compilation_vms: true
  vm_type: compilation
  network: internetless
