# bosh -e ipv4 ucc cloud-config-vsphere.yml
azs:
- name: z1
  cloud_properties:
    datacenters:
    - name: dc
      clusters:
      - cl:
          resource_pool: BOSH-IPv4

vm_types:
- name: small
  cloud_properties:
    cpu: 1
    ram: 512
    disk: 1024
- name: compilation
  cloud_properties:
    cpu: 4
    ram: 4096
    disk: 3072
- name: concourse-workers
  cloud_properties:
    cpu: 4
    ram: 8192
    disk: 32_768

disk_types:
- name: default
  disk_size: 1024

networks:
- name: default
  type: manual
  subnets:
  - range: 10.0.9.0/24
    gateway: 10.0.9.1
    static: [ 10.0.9.161-10.0.9.165 ]
    azs: [ z1 ]
    cloud_properties:
      name: VM Network
- name: guest
  type: manual
  subnets:
  - range: 10.2.0.0/24
    gateway: 10.2.0.1
    static: [ 10.2.0.224-10.2.0.239 ]
    azs: [ z1 ]
    cloud_properties:
      name: Guest

compilation:
  workers: 5
  reuse_compilation_vms: true
  vm_type: compilation
  network: default
  az: z1
