azs:
- name: z1

vm_types:
- name: compilation
  cloud_properties:
    instance_type: Standard_A3
- name: standard_a0
  cloud_properties:
    instance_type: Standard_A0

disk_types:
- name: default
  disk_size: 10_240

networks:
- name: default
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    reserved: [10.0.0.2-10.0.0.3]
    dns: [168.63.129.16]
    azs: [z1]
    cloud_properties:
      virtual_network_name: boshnet
      subnet_name: bosh

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: compilation
  network: default
