azs:
- name: z1
compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: compilation
  workers: 1
disk_types:
- disk_size: 3072
  name: default
networks:
- name: default
  subnets:
  - azs:
    - z1
    cloud_properties:
      subnet_name: bosh
      virtual_network_name: boshnet
    dns:
    - 168.63.129.16
    gateway: 10.0.0.1
    range: 10.0.0.0/24
    reserved:
    - 10.0.0.2-10.0.0.3
  type: manual
- name: vip
  type: vip
vm_types:
- cloud_properties:
    instance_type: Standard_D2_V3
  name: compilation
- cloud_properties:
    ephemeral_disk:
      use_root_disk: true
    instance_type: Standard_A0
  name: standard_a0
