azs:
- cloud_properties:
    datacenters:
    - clusters:
      - cl:
          resource_pool: BOSH
      name: dc
  cpi: vsphere
  name: vsphere
compilation:
  az: vsphere
  network: guest
  reuse_compilation_vms: true
  vm_type: compilation
  workers: 5
disk_types:
- disk_size: 1024
  name: default
networks:
- name: guest
  subnets:
  - azs:
    - vsphere
    cloud_properties:
      name: Guest
    dns:
    - 10.2.0.1
    - 8.8.8.8
    gateway: 10.2.0.1
    range: 10.2.0.0/24
    reserved:
    - 10.2.0.1-10.2.0.240
    - 10.2.0.251-10.2.0.255
  type: manual
vm_types:
- cloud_properties:
    cpu: 1
    disk: 1024
    ram: 512
  name: small
- cloud_properties:
    cpu: 4
    disk: 3072
    ram: 4096
  name: compilation
- cloud_properties:
    cpu: 4
    disk: 65536
    ram: 8192
  name: concourse-workers
