azs:
- cloud_properties:
    zone: us-central1-b
  name: us-central1-b
compilation:
  az: us-central1-b
  network: concourse
  reuse_compilation_vms: true
  vm_type: n1-highcpu-4
  workers: 1
disk_types:
- cloud_properties:
    type: pd-ssd
  disk_size: 5120
  name: db
- cloud_properties:
    type: pd-standard
  disk_size: 5120
  name: nginx
networks:
- name: concourse
  subnets:
  - azs:
    - us-central1-b
    cloud_properties:
      network_name: cf
      tags:
      - cf-internal
      - cf-bosh
    dns:
    - 10.128.0.2
    - 8.8.8.8
    gateway: 10.128.0.1
    range: 10.128.0.0/20
    reserved:
    - 10.128.0.2
    - 10.128.0.3
  type: manual
- name: vip
  type: vip
vm_types:
- cloud_properties:
    machine_type: f1-micro
    root_disk_size_gb: 10
    root_disk_type: pd-standard
  name: f1-micro
- cloud_properties:
    machine_type: g1-small
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: g1-small
- cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 100
    root_disk_type: pd-standard
  name: concourse
- cloud_properties:
    machine_type: n1-highcpu-4
    root_disk_size_gb: 15
    root_disk_type: pd-standard
  name: n1-highcpu-4
