compilation:
  network: dynamic
  reuse_compilation_vms: true
  vm_type: c4.large
  workers: 1
disk_types:
- cloud_properties:
    type: gp2
  disk_size: 5120
  name: concourse
- cloud_properties:
    type: gp2
  disk_size: 5120
  name: nginx
env:
  bosh:
    password: $6$cunnie$GbaS32DMXiaAGYbD/wmNRgJqjHeXnUsXBfp3MgyYntmxIk9XOxM/K3aIKBCCnFGvyc3kCFn61VqatGUEHAr.x/
networks:
- cloud_properties:
    subnet: subnet-1c90ef6b
  name: dynamic
  type: dynamic
- cloud_properties:
    security_groups:
    - concourse
    subnet: subnet-1c90ef6b
  name: dynamic-concourse
  type: dynamic
- name: default
  subnets:
  - cloud_properties:
      security_groups:
      - default
      subnet: subnet-1c90ef6b
    dns:
    - 10.0.0.2
    - 10.0.0.6
    gateway: 10.0.0.1
    range: 10.0.0.0/24
    reserved:
    - 10.0.0.2 - 10.0.0.10
  type: manual
- name: manual-concourse
  subnets:
  - cloud_properties:
      security_groups:
      - concourse
      subnet: subnet-1c90ef6b
    dns:
    - 10.0.0.6
    - 10.0.0.2
    gateway: 10.0.0.1
    range: 10.0.0.0/24
    reserved:
    - 10.0.0.2 - 10.0.0.10
  type: manual
- cloud_properties:
    security_groups:
    - default
    subnet: subnet-1c90ef6b
  name: dynamic-wide-open
  type: dynamic
- name: vip
  type: vip
properties:
  aws:
    default_security_groups:
    - bosh
vm_types:
- cloud_properties:
    availability_zone: us-east-1a
    ephemeral_disk:
      size: 4000
      type: gp2
    instance_type: t3.nano
  env:
    bosh:
      password: $6$cunnie$GbaS32DMXiaAGYbD/wmNRgJqjHeXnUsXBfp3MgyYntmxIk9XOxM/K3aIKBCCnFGvyc3kCFn61VqatGUEHAr.x/
  name: t3.nano
- cloud_properties:
    availability_zone: us-east-1a
    ephemeral_disk:
      size: 100000
      type: gp2
    instance_type: t3.micro
  env:
    bosh:
      password: $6$cunnie$GbaS32DMXiaAGYbD/wmNRgJqjHeXnUsXBfp3MgyYntmxIk9XOxM/K3aIKBCCnFGvyc3kCFn61VqatGUEHAr.x/
  name: t3.micro.100G
- cloud_properties:
    availability_zone: us-east-1a
    ephemeral_disk:
      size: 25000
      type: gp2
    instance_type: t3.micro
  env:
    bosh:
      password: $6$cunnie$GbaS32DMXiaAGYbD/wmNRgJqjHeXnUsXBfp3MgyYntmxIk9XOxM/K3aIKBCCnFGvyc3kCFn61VqatGUEHAr.x/
  name: t3.micro
- cloud_properties:
    availability_zone: us-east-1a
    ephemeral_disk:
      size: 5000
      type: gp2
    instance_type: t3.micro
  env:
    bosh:
      password: $6$cunnie$GbaS32DMXiaAGYbD/wmNRgJqjHeXnUsXBfp3MgyYntmxIk9XOxM/K3aIKBCCnFGvyc3kCFn61VqatGUEHAr.x/
  name: default
- cloud_properties:
    availability_zone: us-east-1a
    ephemeral_disk:
      size: 4000
      type: gp2
    instance_type: c4.large
  env:
    bosh:
      password: $6$cunnie$GbaS32DMXiaAGYbD/wmNRgJqjHeXnUsXBfp3MgyYntmxIk9XOxM/K3aIKBCCnFGvyc3kCFn61VqatGUEHAr.x/
  name: c4.large
