# bosh deploy -nd ipv6 ipv6-lite.yml
---
name: ipv6

releases:
- { name: os-conf, version: latest }
- { name: dhcpd, version: latest }

stemcells:
- alias: ubuntu
  os: ubuntu-xenial
  version: latest
- alias: centos
  os: centos-7
  version: latest

instance_groups:
- name: ipv6-centos
  instances: 1
  networks:
  - name: default
  vm_type: default
  stemcell: centos
  jobs:
  - release: os-conf
    name: enable_ipv6
  - release: dhcpd
    name: dhclient_ipv6
- name: ipv6-ubuntu
  instances: 1
  networks:
  - name: default
  vm_type: default
  stemcell: ubuntu
  jobs:
  - release: os-conf
    name: enable_ipv6
  - release: dhcpd
    name: dhclient_ipv6

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
