# manifest for BOSH performance testing
name: minimal

releases: []

stemcells:
- alias: centos
  os: centos-7
  version: latest

update:
  canaries: 0
  max_in_flight: 10
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

instance_groups:
- name: minimal
  jobs: []
  instances: 2
  vm_type: small
  stemcell: centos
  networks:
  - name: internetless
    static_ips:
    - 192.168.0.3
    - 192.168.0.4
