# manifest for NCP version testing
#
# `bosh -d ncp deploy ncp.yml`
name: ncp

releases: []

stemcells:
- alias: 621.125
  os: ubuntu-xenial
  version: 621.125

update:
  canaries: 0
  max_in_flight: 10
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

instance_groups:
- name: openvswitch
  jobs:
  - name: openvswitch
    release: nsx-cf-cni
  - name: nsx-node-agent
    release: nsx-cf-cni
  instances: 1
  vm_type: small
  stemcell: 621.125
  azs: [z1]
  networks:
  - name: default
- name: openvswitch-builtin-module
  jobs:
  - name: openvswitch-builtin-module
    release: nsx-cf-cni
  - name: nsx-node-agent
    release: nsx-cf-cni
  instances: 1
  vm_type: small
  stemcell: 621.125
  azs: [z1]
  networks:
  - name: default

releases:
- name: nsx-cf-cni
  version: 3.2.0.47582919
# version: 3.2.0.46917173
# version: 3.1.0.17170700
# version: 3.0.2.17079862 # 3.0.2.2
# version: 3.0.2.16863080 # 3.0.2.? broke
# version: 2.5.1.15287458 # 2.5.1
