# manifest for NCP version testing
#
# `bosh -d ncp deploy ncp.yml`
name: ncp

releases: []

stemcells:
- alias: 621.101
  os: ubuntu-xenial
  version: 621.101
- alias: 0.6
  os: ubuntu-bionic
  version: 0.6

update:
  canaries: 0
  max_in_flight: 10
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

instance_groups:
# - name: 0.6
#   jobs:
#   - name: openvswitch
#     release: nsx-cf-cni
#   instances: 1
#   vm_type: small
#   stemcell: 0.6
#   azs: [z1]
#   networks:
#   - name: default
- name: 621.101
  jobs:
  - name: openvswitch
    release: nsx-cf-cni
  instances: 1
  vm_type: small
  stemcell: 621.101
  azs: [z1]
  networks:
  - name: default

releases:
- name: nsx-cf-cni
  version: 3.1.0.17170700
# version: 3.0.2.17079862 # 3.0.2.2
# version: 2.5.1.15287458 # 2.5.1
