# manifest for NCP version testing
#
# `bosh -d ncp deploy ncp.yml`
name: ncp

releases: []

stemcells:
- alias: 621.92
  os: ubuntu-xenial
  version: 621.92
- alias: 621.93
  os: ubuntu-xenial
  version: 621.93

update:
  canaries: 0
  max_in_flight: 10
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

instance_groups:
- name: 621.93
  jobs:
  - name: openvswitch
    release: nsx-cf-cni
  instances: 1
  vm_type: small
  stemcell: 621.93
  azs: [z1]
  networks:
  - name: default

releases:
- name: nsx-cf-cni
# version: 3.0.2.16863080 # 3.0.2
  version: 3.0.2.17079862 # 3.0.2.2
