# manifest for NCP version testing
#
# `bosh -d ncp deploy ncp.yml`
name: ncp

releases: []

stemcells:
- alias: 621.75
  os: ubuntu-xenial
  version: 621.75
- alias: 621.76
  os: ubuntu-xenial
  version: 621.76
- alias: 621.77
  os: ubuntu-xenial
  version: 621.77

update:
  canaries: 0
  max_in_flight: 10
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000

instance_groups:
- name: ncp
  jobs:
  - name: openvswitch
    release: nsx-cf-cni
  instances: 1
  vm_type: small
  stemcell: 621.77
  azs: [z1]
  networks:
  - name: default

releases:
- name: nsx-cf-cni
  version: 3.0.1.16118386
# version: 3.0.2.16453843
