---
name: nginx

releases:
- name: nginx
  version: latest

stemcells:
- alias: centos
  os: centos-7
  version: latest

instance_groups:
- name: nginx-red
  instances: 1
  vm_type: default
  vm_extensions: [lb]
  stemcell: centos
  networks:
  - name: manual
    static_ips:
    - 10.85.57.21
  jobs:
  - name: nginx
    release: nginx
    properties:
      pre_start: |
        #!/bin/bash -ex
        NGINX_DIR=/var/vcap/data/nginx/document_root
        if [ ! -d $NGINX_DIR ]; then
          mkdir -p $NGINX_DIR
          cd $NGINX_DIR
          COLOR=red
          cat > index.html <<EOF
              <html><head><title>$COLOR</title>
              </head><body><h1 style='color: $COLOR'>10.85.57.21 $COLOR</h1>
              </body></html>
        EOF
        fi
      nginx_conf: |
        worker_processes  1;
        error_log /var/vcap/sys/log/nginx/error.log   info;
        events {
          worker_connections  1024;
        }
        http {
          include /var/vcap/packages/nginx/conf/mime.types;
          default_type  application/octet-stream;
          sendfile        on;
          keepalive_timeout  65;
          server_names_hash_bucket_size 64;
          server {
            server_name _; # invalid value which will never trigger on a real hostname.
            listen 80;
            access_log /var/vcap/sys/log/nginx/access.log;
            error_log /var/vcap/sys/log/nginx/error.log;
            root /var/vcap/data/nginx/document_root;
          }
        }
- name: nginx-green
  instances: 1
  vm_type: default
  vm_extensions: [lb]
  stemcell: centos
  networks:
  - name: manual
    static_ips:
    - 10.85.57.22
  jobs:
  - name: nginx
    release: nginx
    properties:
      pre_start: |
        #!/bin/bash -ex
        NGINX_DIR=/var/vcap/data/nginx/document_root
        if [ ! -d $NGINX_DIR ]; then
          mkdir -p $NGINX_DIR
          cd $NGINX_DIR
          COLOR=green
          cat > index.html <<EOF
              <html><head><title>$COLOR</title>
              </head><body><h1 style='color: $COLOR'>10.85.57.22 $COLOR</h1>
              </body></html>
        EOF
        fi
      nginx_conf: |
        worker_processes  1;
        error_log /var/vcap/sys/log/nginx/error.log   info;
        events {
          worker_connections  1024;
        }
        http {
          include /var/vcap/packages/nginx/conf/mime.types;
          default_type  application/octet-stream;
          sendfile        on;
          keepalive_timeout  65;
          server_names_hash_bucket_size 64;
          server {
            server_name _; # invalid value which will never trigger on a real hostname.
            listen 80;
            access_log /var/vcap/sys/log/nginx/access.log;
            error_log /var/vcap/sys/log/nginx/error.log;
            root /var/vcap/data/nginx/document_root;
          }
        }
- name: nginx-blue
  instances: 1
  vm_type: default
  vm_extensions: [lb]
  stemcell: centos
  networks:
  - name: manual
    static_ips:
    - 10.85.57.23
  jobs:
  - name: nginx
    release: nginx
    properties:
      pre_start: |
        #!/bin/bash -ex
        NGINX_DIR=/var/vcap/data/nginx/document_root
        if [ ! -d $NGINX_DIR ]; then
          mkdir -p $NGINX_DIR
          cd $NGINX_DIR
          COLOR=blue
          cat > index.html <<EOF
              <html><head><title>$COLOR</title>
              </head><body><h1 style='color: $COLOR'>10.85.57.23 $COLOR</h1>
              </body></html>
        EOF
        fi
      nginx_conf: |
        worker_processes  1;
        error_log /var/vcap/sys/log/nginx/error.log   info;
        events {
          worker_connections  1024;
        }
        http {
          include /var/vcap/packages/nginx/conf/mime.types;
          default_type  application/octet-stream;
          sendfile        on;
          keepalive_timeout  65;
          server_names_hash_bucket_size 64;
          server {
            server_name _; # invalid value which will never trigger on a real hostname.
            listen 80;
            access_log /var/vcap/sys/log/nginx/access.log;
            error_log /var/vcap/sys/log/nginx/error.log;
            root /var/vcap/data/nginx/document_root;
          }
        }

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
