instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: sslip.io-dns-server
    release: sslip.io
  name: sslip.io
  networks:
  - name: default
  stemcell: xenial
  vm_type: small
name: sslip.io-dns-server
releases:
- name: sslip.io
  version: latest
stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest
update:
  canaries: 0
  canary_watch_time: 30000-600000
  max_in_flight: 10
  update_watch_time: 5000-600000
