---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cunnie/fedora-golang-bosh

inputs:
- name: cunnie-deployments
- name: bosh-deployment

outputs:
- name: cunnie-deployments-with-state

params:
  # vainly default branch to master, but it's always overridden from the pipeline
  DEPLOYMENTS_BRANCH: 'master'
  DEPLOYMENTS_YML: ''
  IAAS: ''

run:
  path: cunnie-deployments/ci/tasks/bosh.sh
