---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/bosh-cli-v2

inputs:
- name: cunnie-deployments
- name: bosh-deployment

params:
  DEPLOYMENTS_YML: ''
  IAAS: ''

run:
  path: cunnie-deployments/ci/tasks/bosh.sh
