# bosh -e aws -d bonnie++ deploy aws.yml
# mkdir /tmp/{standard,gp2,io1}
# bosh -e aws -d bonnie++ run-errand standard --json | jq -r .Tables[].Rows[].stdout > m4_large_standard.txt
# bosh -e aws -d bonnie++ run-errand gp2      --json | jq -r .Tables[].Rows[].stdout > m4_large_gp2.txt
# bosh -e aws -d bonnie++ run-errand io1      --json | jq -r .Tables[].Rows[].stdout > m4_large_io1.txt
---
name: bonnie++

instance_groups:
- name: standard
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: bonnie++
    release: bonnie++
    properties:
      dir: /var/vcap/store/bonnie++
  vm_type: default
  persistent_disk_type: standard
  stemcell: default
  networks:
  - name: default
- name: gp2
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: bonnie++
    release: bonnie++
    properties:
      dir: /var/vcap/store/bonnie++
  vm_type: default
  persistent_disk_type: gp2
  stemcell: default
  networks:
  - name: default
- name: io1
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: bonnie++
    release: bonnie++
    properties:
      dir: /var/vcap/store/bonnie++
  vm_type: default
  persistent_disk_type: io1
  stemcell: default
  networks:
  - name: default

releases:
- name: bonnie++
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000
