# bosh -e gce -d bonnie++ deploy gce.yml
# bosh -e gce -d bonnie++ run-errand pd-standard --json | jq -r .Tables[].Rows[].stdout > gce_pd-standard.txt
# bosh -e gce -d bonnie++ run-errand pd-ssd      --json | jq -r .Tables[].Rows[].stdout > gce_pd-ssd.txt
---
name: bonnie++

instance_groups:
- name: pd-standard
  azs: [us-central1-b]
  lifecycle: errand
  instances: 1
  jobs:
  - name: bonnie++
    release: bonnie++
    properties:
      dir: /var/vcap/store/bonnie++
      args: -m gce_pd-standard
  vm_type: default
  persistent_disk_type: pd-standard
  stemcell: default
  networks:
  - name: manual
- name: pd-ssd
  azs: [us-central1-b]
  lifecycle: errand
  instances: 1
  jobs:
  - name: bonnie++
    release: bonnie++
    properties:
      dir: /var/vcap/store/bonnie++
      args: -m gce_pd-ssd
  vm_type: default
  persistent_disk_type: pd-ssd
  stemcell: default
  networks:
  - name: manual

releases:
- name: bonnie++
  version: latest

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000
