# bosh -e ipv4 -d bonnie++ deploy vsphere.yml
# bosh -e ipv4 -d bonnie++ run-errand freenas --json | jq -r .Tables[].Rows[].stdout > vsphere_freenas.txt
# bosh -e ipv4 -d bonnie++ run-errand sata    --json | jq -r .Tables[].Rows[].stdout > vsphere_sata.txt
# bosh -e ipv4 -d bonnie++ run-errand nvme    --json | jq -r .Tables[].Rows[].stdout > vsphere_nvme.txt
---
name: bonnie++

instance_groups:
- name: freenas
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: bonnie++
    release: bonnie++
    properties:
      dir: /var/vcap/store/bonnie++
      args: -m vsphere_freenas
  vm_type: freenas
  persistent_disk_type: freenas
  stemcell: default
  networks:
  - name: default
- name: sata
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: bonnie++
    release: bonnie++
    properties:
      dir: /var/vcap/store/bonnie++
      args: -m vsphere_sata
  vm_type: sata
  persistent_disk_type: sata
  stemcell: default
  networks:
  - name: default
- name: nvme
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: bonnie++
    release: bonnie++
    properties:
      dir: /var/vcap/store/bonnie++
      args: -m vsphere_nvme
  vm_type: nvme
  persistent_disk_type: nvme
  stemcell: default
  networks:
  - name: default

releases:
- name: bonnie++
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000
