# bosh -e aws -d gobonniego -n deploy aws.yml
# bosh -e aws -d gobonniego run-errand standard     --json | jq -r .Tables[].Rows[].stdout > aws_standard.json
# bosh -e aws -d gobonniego run-errand standard-256 --json | jq -r .Tables[].Rows[].stdout > aws_standard-256.json
# bosh -e aws -d gobonniego run-errand standard-lr  --json | jq -r .Tables[].Rows[].stdout > aws_standard-lr.json
# bosh -e aws -d gobonniego run-errand gp2          --json | jq -r .Tables[].Rows[].stdout > aws_gp2.json
# bosh -e aws -d gobonniego run-errand gp2-256      --json | jq -r .Tables[].Rows[].stdout > aws_gp2-256.json
# bosh -e aws -d gobonniego run-errand gp2-lr       --json | jq -r .Tables[].Rows[].stdout > aws_gp2-lr.json
# bosh -e aws -d gobonniego run-errand io1          --json | jq -r .Tables[].Rows[].stdout > aws_io1.json
# bosh -e aws -d gobonniego run-errand io1-256      --json | jq -r .Tables[].Rows[].stdout > aws_io1-256.json
---
name: gobonniego

instance_groups:
- name: standard
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: gobonniego
    release: gobonniego
    properties:
      dir: /var/vcap/store/gobonniego
      args: -runs 10 -json
  vm_type: default
  persistent_disk_type: standard
  stemcell: default
  networks:
  - name: default
- name: standard-256
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: gobonniego
    release: gobonniego
    properties:
      dir: /var/vcap/store/gobonniego
      args: -runs 10 -json
  vm_type: default
  persistent_disk_type: standard-256
  stemcell: default
  networks:
  - name: default
- name: standard-lr
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: gobonniego
    release: gobonniego
    properties:
      dir: /var/vcap/store/gobonniego
      args: -runs 50 -json
  vm_type: default
  persistent_disk_type: standard
  stemcell: default
  networks:
  - name: default
- name: gp2
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: gobonniego
    release: gobonniego
    properties:
      dir: /var/vcap/store/gobonniego
      args: -runs 10 -json
  vm_type: default
  persistent_disk_type: gp2
  stemcell: default
  networks:
  - name: default
- name: gp2-256
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: gobonniego
    release: gobonniego
    properties:
      dir: /var/vcap/store/gobonniego
      args: -runs 10 -json
  vm_type: default
  persistent_disk_type: gp2-256
  stemcell: default
  networks:
  - name: default
- name: gp2-lr
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: gobonniego
    release: gobonniego
    properties:
      dir: /var/vcap/store/gobonniego
      args: -runs 100 -json
  vm_type: default
  persistent_disk_type: gp2
  stemcell: default
  networks:
  - name: default
- name: io1
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: gobonniego
    release: gobonniego
    properties:
      dir: /var/vcap/store/gobonniego
      args: -runs 10 -json
  vm_type: default
  persistent_disk_type: io1
  stemcell: default
  networks:
  - name: default
- name: io1-256
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: gobonniego
    release: gobonniego
    properties:
      dir: /var/vcap/store/gobonniego
      args: -runs 10 -json
  vm_type: default
  persistent_disk_type: io1-256
  stemcell: default
  networks:
  - name: default

releases:
- name: gobonniego
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000
