# bosh -e gce -d gobonniego deploy gce.yml
# bosh -e gce -d gobonniego run-errand pd-standard     --json | jq -r .Tables[].Rows[].stdout > gce_pd-standard.json
# bosh -e gce -d gobonniego run-errand pd-standard-256 --json | jq -r .Tables[].Rows[].stdout > gce_pd-standard-256.json
# bosh -e gce -d gobonniego run-errand pd-ssd          --json | jq -r .Tables[].Rows[].stdout > gce_pd-ssd.json
# bosh -e gce -d gobonniego run-errand pd-ssd-256      --json | jq -r .Tables[].Rows[].stdout > gce_pd-ssd-256.json
---
name: gobonniego

instance_groups:
- name: pd-standard
  azs: [us-central1-b]
  lifecycle: errand
  instances: 1
  jobs:
  - name: gobonniego
    release: gobonniego
    properties:
      dir: /var/vcap/store/gobonniego
      args: -runs 10 -json
  vm_type: default
  persistent_disk_type: pd-standard
  stemcell: default
  networks:
  - name: concourse
- name: pd-standard-256
  azs: [us-central1-b]
  lifecycle: errand
  instances: 1
  jobs:
  - name: gobonniego
    release: gobonniego
    properties:
      dir: /var/vcap/store/gobonniego
      args: -runs 10 -json
  vm_type: default
  persistent_disk_type: pd-standard-256
  stemcell: default
  networks:
  - name: concourse
- name: pd-ssd
  azs: [us-central1-b]
  lifecycle: errand
  instances: 1
  jobs:
  - name: gobonniego
    release: gobonniego
    properties:
      dir: /var/vcap/store/gobonniego
      args: -runs 10 -json
  vm_type: default
  persistent_disk_type: pd-ssd
  stemcell: default
  networks:
  - name: concourse
- name: pd-ssd-256
  azs: [us-central1-b]
  lifecycle: errand
  instances: 1
  jobs:
  - name: gobonniego
    release: gobonniego
    properties:
      dir: /var/vcap/store/gobonniego
      args: -runs 10 -json
  vm_type: default
  persistent_disk_type: pd-ssd-256
  stemcell: default
  networks:
  - name: concourse

releases:
- name: gobonniego
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000
