# bosh -e ipv4 -d gobonniego -n deploy vsphere.yml
# bosh -e ipv4 -d gobonniego run-errand freenas --json | jq -r .Tables[].Rows[].stdout > vsphere_freenas.json
# bosh -e ipv4 -d gobonniego run-errand sata    --json | jq -r .Tables[].Rows[].stdout > vsphere_sata.json
# bosh -e ipv4 -d gobonniego run-errand nvme    --json | jq -r .Tables[].Rows[].stdout > vsphere_nvme.json
---
name: gobonniego

instance_groups:
- name: freenas
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: gobonniego
    release: gobonniego
    properties:
      dir: /var/vcap/store/gobonniego
      args: -runs 10 -json
  vm_type: freenas
  persistent_disk_type: freenas
  stemcell: default
  networks:
  - name: default
- name: sata
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: gobonniego
    release: gobonniego
    properties:
      dir: /var/vcap/store/gobonniego
      args: -runs 10 -json
  vm_type: sata
  persistent_disk_type: sata
  stemcell: default
  networks:
  - name: default
- name: nvme
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: gobonniego
    release: gobonniego
    properties:
      dir: /var/vcap/store/gobonniego
      args: -runs 10 -json
  vm_type: nvme
  persistent_disk_type: nvme
  stemcell: default
  networks:
  - name: default

releases:
- name: gobonniego
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000
